apiVersion: v1
kind: Service
metadata:
  name: {{ include "ext-gcp-pubsub-emulator.fullname" . }}
  labels:
    {{- include "ext-gcp-pubsub-emulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ext-gcp-pubsub-emulator.selectorLabels" . | nindent 4 }}
