apiVersion: v2
name: microserv-io
description: A Helm chart for deploying Microserv.io's infrastructure

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.3.3
    condition: postgresql.enabled
  - name: oauth-credentials-server
    alias: oauthCredentialsServer
    repository: file://../components/oauth-credentials-server
    version: 0.1.0
    condition: oauthCredentialsServer.enabled
  - name: internal-core-system
    alias: internalCoreSystem
    repository: file://../components/internal-core-system
    version: 0.1.0
    condition: internal-core-system.enabled
  - name: internal-gql-gateway
    alias: internalGqlGateway
    repository: file://../components/internal-gql-gateway
    version: 0.1.0
    condition: internal-gql-gateway.enabled
  - name: gcp-pubsub-emulator
    alias: gcpPubsubEmulator
    repository: file://../thirdparty/gcp-pubsub-emulator
    version: 0.1.0
    condition: gcp-pubsub-emulator.enabled
